services:
  db:
    image: postgres:14-alpine
    container_name: meu_projeto_db_container
    environment:
      POSTGRES_DB: meu_projeto_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
